import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const EVENEMENTS = [
  { slug: "festival-musique-littoral", titre: "Festival de Musique du Littoral 2026", categorie: "Festival", date: "14 â€” 16 Mai 2026", heure: "16h00 â€” 02h00", lieu: "Plage de Grand-Bassam", ville: "Grand-Bassam", image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80", badge: "A venir", badgeColor: "bg-blue-500", prix: "5 000 â€” 25 000 FCFA", capacite: "5 000 / soir", duree: "3 jours", artistes: "30+", organisateur: "COTIERE EVENT", description: "Le Festival de Musique du Littoral est l'evenement musical incontournable de la cote ivoirienne. Pendant 3 jours, la plage mythique de Grand-Bassam se transforme en scene geante accueillant plus de 30 artistes locaux et internationaux.", programme: ["Vendredi 14 Mai : Ouverture officielle & artistes locaux (16h â€” 02h)", "Samedi 15 Mai : Tetes d affiche & artistes internationaux (16h â€” 02h)", "Dimanche 16 Mai : Grande finale & feu d artifice (16h â€” 02h)"] },
  { slug: "festival-jazz-bassam", titre: "Festival Jazz & Blues de Bassam", categorie: "Festival", date: "2 â€” 3 Aout 2026", heure: "18h00 â€” 01h00", lieu: "Hotel Residence Bassam", ville: "Grand-Bassam", image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&q=80", badge: "Nouveaute", badgeColor: "bg-indigo-500", prix: "10 000 â€” 30 000 FCFA", capacite: "800 / soir", duree: "2 jours", artistes: "15+", organisateur: "COTIERE EVENT & Jazz Club Abidjan", description: "Une nuit de jazz et blues en bord de mer avec des musiciens de renommee internationale.", programme: [] },
  { slug: "festival-afrobeat-abidjan", titre: "Afrobeat Summer Festival", categorie: "Festival", date: "22 â€” 23 Aout 2026", heure: "17h00 â€” 03h00", lieu: "Stade Felix Houphouet-Boigny", ville: "Abidjan", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80", badge: "Bientot", badgeColor: "bg-pink-500", prix: "15 000 â€” 50 000 FCFA", capacite: "20 000 / soir", duree: "2 jours", artistes: "20+", organisateur: "COTIERE EVENT & Live Nation Africa", description: "Le plus grand festival afrobeat de Cote d Ivoire avec 20 artistes sur 2 scenes.", programme: [] },
  { slug: "gala-entrepreneurs-cotiere", titre: "Gala des Entrepreneurs du Littoral", categorie: "Gala", date: "7 Juin 2026", heure: "19h00 â€” 00h00", lieu: "Hotel Palm Club", ville: "Abidjan â€” Cocody", image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80", badge: "Places limitees", badgeColor: "bg-amber-500", prix: "50 000 â€” 150 000 FCFA", capacite: "300 invites", duree: "1 soir", organisateur: "COTIERE Opportunites", description: "Soiree de prestige reunissant les entrepreneurs, investisseurs et decideurs economiques du littoral ivoirien.", programme: [] },
  { slug: "gala-culture-cotiere", titre: "Gala de la Culture Cotiere", categorie: "Gala", date: "28 Juin 2026", heure: "19h30 â€” 23h30", lieu: "Sofitel Abidjan Hotel Ivoire", ville: "Abidjan", image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600&q=80", badge: "Prestige", badgeColor: "bg-rose-500", prix: "75 000 â€” 200 000 FCFA", capacite: "400 invites", duree: "1 soir", organisateur: "Ministere de la Culture & COTIERE", description: "Soiree de gala celebrant les artistes, createurs et acteurs culturels du littoral ivoirien.", programme: [] },
  { slug: "gala-sport-cotiere", titre: "Gala du Sport Cotier 2026", categorie: "Gala", date: "15 Novembre 2026", heure: "19h00 â€” 23h00", lieu: "Palais de la Culture", ville: "Abidjan â€” Treichville", image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&q=80", badge: "A venir", badgeColor: "bg-blue-500", prix: "30 000 â€” 80 000 FCFA", capacite: "600 invites", duree: "1 soir", organisateur: "COTIERE Sport & FIF", description: "Remise des trophees aux meilleurs sportifs et clubs du littoral ivoirien pour la saison 2026.", programme: [] },
  { slug: "forum-tourisme-cotier", titre: "Forum du Tourisme Cotier Ivoirien", categorie: "Conference", date: "21 â€” 22 Juin 2026", heure: "08h30 â€” 18h00", lieu: "Centre de Conferences de Grand-Bassam", ville: "Grand-Bassam", image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80", badge: "Inscription ouverte", badgeColor: "bg-green-500", prix: "Gratuit â€” 30 000 FCFA", capacite: "500 participants", duree: "2 jours", organisateur: "COTIERE & Ministere du Tourisme", description: "2 jours de conferences, ateliers et echanges autour du developpement touristique du littoral ivoirien.", programme: [] },
  { slug: "sommet-economie-bleue", titre: "Sommet de l Economie Bleue", categorie: "Conference", date: "10 â€” 11 Septembre 2026", heure: "09h00 â€” 17h30", lieu: "CICG Abidjan", ville: "Abidjan â€” Plateau", image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&q=80", badge: "Inscription ouverte", badgeColor: "bg-green-500", prix: "Gratuit â€” 50 000 FCFA", capacite: "800 participants", duree: "2 jours", organisateur: "COTIERE & Union Africaine", description: "Sommet international dedie a l economie maritime, la peche durable et les ressources cotieres.", programme: [] },
  { slug: "conference-numerique-cotiere", titre: "Conference Numerique & Innovation Cotiere", categorie: "Conference", date: "5 Octobre 2026", heure: "09h00 â€” 18h00", lieu: "Universite Felix Houphouet-Boigny", ville: "Abidjan â€” Cocody", image: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600&q=80", badge: "Bientot", badgeColor: "bg-cyan-500", prix: "Gratuit", capacite: "600 participants", duree: "1 jour", organisateur: "COTIERE & Ministere du Numerique", description: "Journee de conferences sur la transformation numerique des entreprises du littoral ivoirien.", programme: [] },
  { slug: "fete-mer-jacqueville", titre: "Fete de la Mer â€” Jacqueville 2026", categorie: "Fete culturelle", date: "4 Juillet 2026", heure: "10h00 â€” 22h00", lieu: "Front de mer de Jacqueville", ville: "Jacqueville", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80", badge: "Entree libre", badgeColor: "bg-teal-500", prix: "Entree libre", capacite: "Illimitee", duree: "1 jour", organisateur: "Mairie de Jacqueville & COTIERE", description: "Grande fete populaire celebrant la mer, les pecheurs et la culture maritime de Jacqueville.", programme: [] },
  { slug: "fete-igname-grand-lahou", titre: "Fete de l Igname â€” Grand-Lahou", categorie: "Fete culturelle", date: "19 Juillet 2026", heure: "09h00 â€” 20h00", lieu: "Place du Marche de Grand-Lahou", ville: "Grand-Lahou", image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&q=80", badge: "Entree libre", badgeColor: "bg-teal-500", prix: "Entree libre", capacite: "Illimitee", duree: "1 jour", organisateur: "Chefferie de Grand-Lahou & COTIERE", description: "Celebration traditionnelle des premieres recoltes d igname avec danses, chants et gastronomie locale.", programme: [] },
  { slug: "carnaval-bassam-2026", titre: "Carnaval de Grand-Bassam 2026", categorie: "Fete culturelle", date: "12 Septembre 2026", heure: "14h00 â€” 22h00", lieu: "Quartier France â€” Grand-Bassam", ville: "Grand-Bassam", image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80", badge: "Populaire", badgeColor: "bg-orange-500", prix: "Entree libre", capacite: "Illimitee", duree: "1 jour", organisateur: "Mairie de Grand-Bassam & COTIERE", description: "Defile de chars, costumes traditionnels et musiques du monde dans les rues historiques de Bassam.", programme: [] },
  { slug: "salon-artisanat-assinie", titre: "Salon de l Artisanat d Assinie", categorie: "Salon", date: "18 â€” 20 Juillet 2026", heure: "09h00 â€” 20h00", lieu: "Village Artisanal d Assinie", ville: "Assinie", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80", badge: "Exposants bienvenus", badgeColor: "bg-purple-500", prix: "2 000 FCFA / jour", capacite: "2 000 visiteurs / jour", duree: "3 jours", organisateur: "Chambre des Metiers & COTIERE", description: "3 jours de decouverte de l artisanat ivoirien : tissage, sculpture, bijouterie, poterie et gastronomie locale.", programme: [] },
  { slug: "salon-gastronomie-cotiere", titre: "Salon de la Gastronomie Cotiere", categorie: "Salon", date: "8 â€” 9 Aout 2026", heure: "10h00 â€” 21h00", lieu: "Esplanade du Port de Peche", ville: "Abidjan â€” Treichville", image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80", badge: "Nouveau", badgeColor: "bg-emerald-500", prix: "3 000 FCFA / jour", capacite: "3 000 visiteurs / jour", duree: "2 jours", organisateur: "COTIERE & Chambre de Commerce", description: "Decouverte des saveurs du littoral : poissons, fruits de mer, attieke et specialites cotieres.", programme: [] },
  { slug: "salon-immobilier-cotier", titre: "Salon de l Immobilier Cotier", categorie: "Salon", date: "17 â€” 18 Octobre 2026", heure: "09h00 â€” 18h00", lieu: "Palais des Congres d Abidjan", ville: "Abidjan â€” Plateau", image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80", badge: "Professionnel", badgeColor: "bg-slate-500", prix: "Gratuit â€” 10 000 FCFA", capacite: "1 500 visiteurs / jour", duree: "2 jours", organisateur: "COTIERE & Chambre Nationale des Promoteurs", description: "Rencontre des promoteurs, investisseurs et acheteurs autour de l immobilier cotier ivoirien.", programme: [] },
  { slug: "tournoi-foot-plage", titre: "Tournoi de Football de Plage â€” Cotiere Cup", categorie: "Sport", date: "9 â€” 10 Aout 2026", heure: "08h00 â€” 20h00", lieu: "Plage de Bassam", ville: "Grand-Bassam", image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&q=80", badge: "Inscriptions ouvertes", badgeColor: "bg-orange-500", prix: "Spectateurs : Gratuit â€” Equipes : 50 000 FCFA", capacite: "16 equipes / 3 000 spectateurs", duree: "2 jours", organisateur: "COTIERE Sport & FIF", description: "Tournoi officiel de beach soccer reunissant 16 equipes du littoral ivoirien pour 2 jours de competition intense.", programme: [] },
  { slug: "marathon-cotier-2026", titre: "Marathon Cotier de Cote d Ivoire", categorie: "Sport", date: "27 Septembre 2026", heure: "06h00 â€” 14h00", lieu: "Depart : Plage de Vridi", ville: "Abidjan â€” Vridi", image: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=600&q=80", badge: "Inscriptions ouvertes", badgeColor: "bg-orange-500", prix: "15 000 â€” 25 000 FCFA", capacite: "2 000 coureurs", duree: "1 jour", organisateur: "COTIERE Sport & Federation d Athletisme", description: "42 km le long du littoral ivoirien, de Vridi a Grand-Bassam. Ouvert aux coureurs amateurs et professionnels.", programme: [] },
  { slug: "tournoi-volleyball-plage", titre: "Tournoi de Volleyball de Plage", categorie: "Sport", date: "25 â€” 26 Octobre 2026", heure: "09h00 â€” 19h00", lieu: "Plage de Gonzagueville", ville: "Port-Bouet", image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&q=80", badge: "Bientot", badgeColor: "bg-blue-500", prix: "Gratuit", capacite: "32 equipes / 1 500 spectateurs", duree: "2 jours", organisateur: "COTIERE Sport & Federation de Volleyball", description: "Tournoi de beach-volley ouvert a tous les niveaux avec 32 equipes mixtes sur les plages de Port-Bouet.", programme: [] },
  { slug: "formation-entrepreneuriat-cotier", titre: "Formation Entrepreneuriat Cotier", categorie: "Formation", date: "13 â€” 14 Juin 2026", heure: "08h30 â€” 17h00", lieu: "Centre de Formation COTIERE", ville: "Grand-Bassam", image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&q=80", badge: "Inscription ouverte", badgeColor: "bg-green-500", prix: "25 000 â€” 50 000 FCFA", capacite: "30 participants", duree: "2 jours", organisateur: "COTIERE Formation", description: "2 jours de formation intensive pour lancer et developper son activite sur le littoral ivoirien.", programme: [] },
  { slug: "formation-metiers-tourisme", titre: "Formation aux Metiers du Tourisme Cotier", categorie: "Formation", date: "20 â€” 22 Juillet 2026", heure: "09h00 â€” 17h00", lieu: "Ecole Hoteliere d Abidjan", ville: "Abidjan â€” Cocody", image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80", badge: "Places limitees", badgeColor: "bg-amber-500", prix: "30 000 â€” 75 000 FCFA", capacite: "25 participants", duree: "3 jours", organisateur: "COTIERE Formation & Ecole Hoteliere", description: "3 jours de formation professionnelle : accueil touristique, guide de voyage, gestion hoteliere et restauration cotiere.", programme: [] },
  { slug: "formation-numerique-pme", titre: "Formation Numerique pour PME du Littoral", categorie: "Formation", date: "3 â€” 4 Octobre 2026", heure: "09h00 â€” 17h00", lieu: "Espace Numerique COTIERE", ville: "Abidjan â€” Plateau", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80", badge: "Nouveau", badgeColor: "bg-cyan-500", prix: "20 000 FCFA", capacite: "20 participants", duree: "2 jours", organisateur: "COTIERE Formation & Ministere du Numerique", description: "2 jours de formation pratique : reseaux sociaux, e-commerce, site web et outils numeriques pour les PME du littoral ivoirien.", programme: [] },
  { slug: "formation-react-native-elite-upwork", titre: "Formation React Native â€” Developpement Mobile", categorie: "Formation", date: "16 Mai 2026", heure: "Lundi â€” Vendredi", lieu: "Elite Upwork â€” Centre de Formation", ville: "Abidjan", image: "/Images/formation.jpeg", badge: "Nouvelle rentree", badgeColor: "bg-red-500", prix: "400 000 FCFA (inscription : 5 000 FCFA)", capacite: "20 participants", duree: "6 mois", organisateur: "Elite Upwork", description: "Formation intensive de 6 mois en developpement mobile React Native avec certificat et stage inclus.", programme: [] },
];

async function main() {
  console.log("Seeding evenements...");
  for (const ev of EVENEMENTS) {
    await prisma.evenement.upsert({
      where: { slug: ev.slug },
      update: { ...ev },
      create: { ...ev },
    });
  }
  console.log(`${EVENEMENTS.length} evenements seeded.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());


